#pragma checksum "C:\Users\attfl\Documents\Visual Studio 2019\Projects\FolderLinkCreator\FolderLinkCreator.UWPUI\MasterEntryControl.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "1A3C6CED2353AE324E1150E18EBD278D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderLinkCreator.UWPUI
{
    partial class MasterEntryControl : 
        global::Windows.UI.Xaml.Controls.UserControl, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18362.1")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private static class XamlBindingSetters
        {
            public static void Set_Windows_UI_Xaml_Controls_TextBox_Text(global::Windows.UI.Xaml.Controls.TextBox obj, global::System.String value, string targetNullValue)
            {
                if (value == null && targetNullValue != null)
                {
                    value = targetNullValue;
                }
                obj.Text = value ?? global::System.String.Empty;
            }
        };

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18362.1")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private class MasterEntryControl_obj1_Bindings :
            global::Windows.UI.Xaml.Markup.IComponentConnector,
            IMasterEntryControl_Bindings
        {
            private global::FolderLinkCreator.UWPUI.MasterEntryControl dataRoot;
            private bool initialized = false;
            private const int NOT_PHASED = (1 << 31);
            private const int DATA_CHANGED = (1 << 30);

            // Fields for each control that has bindings.
            private global::Windows.UI.Xaml.Controls.TextBox obj2;
            private global::Windows.UI.Xaml.Controls.TextBox obj4;

            private MasterEntryControl_obj1_BindingsTracking bindingsTracking;

            public MasterEntryControl_obj1_Bindings()
            {
                this.bindingsTracking = new MasterEntryControl_obj1_BindingsTracking(this);
            }

            // IComponentConnector

            public void Connect(int connectionId, global::System.Object target)
            {
                switch(connectionId)
                {
                    case 2: // MasterEntryControl.xaml line 41
                        this.obj2 = (global::Windows.UI.Xaml.Controls.TextBox)target;
                        this.bindingsTracking.RegisterTwoWayListener_2(this.obj2);
                        break;
                    case 4: // MasterEntryControl.xaml line 58
                        this.obj4 = (global::Windows.UI.Xaml.Controls.TextBox)target;
                        this.bindingsTracking.RegisterTwoWayListener_4(this.obj4);
                        break;
                    default:
                        break;
                }
            }

            // IMasterEntryControl_Bindings

            public void Initialize()
            {
                if (!this.initialized)
                {
                    this.Update();
                }
            }
            
            public void Update()
            {
                this.Update_(this.dataRoot, NOT_PHASED);
                this.initialized = true;
            }

            public void StopTracking()
            {
                this.bindingsTracking.ReleaseAllListeners();
                this.initialized = false;
            }

            public void DisconnectUnloadedObject(int connectionId)
            {
                throw new global::System.ArgumentException("No unloadable elements to disconnect.");
            }

            public bool SetDataRoot(global::System.Object newDataRoot)
            {
                this.bindingsTracking.ReleaseAllListeners();
                if (newDataRoot != null)
                {
                    this.dataRoot = (global::FolderLinkCreator.UWPUI.MasterEntryControl)newDataRoot;
                    return true;
                }
                return false;
            }

            public void Loading(global::Windows.UI.Xaml.FrameworkElement src, object data)
            {
                this.Initialize();
            }

            // Update methods for each path node used in binding steps.
            private void Update_(global::FolderLinkCreator.UWPUI.MasterEntryControl obj, int phase)
            {
                this.bindingsTracking.UpdateChildListeners_(obj);
                if (obj != null)
                {
                    if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
                    {
                        this.Update_TargetFolderPath(obj.TargetFolderPath, phase);
                        this.Update_LinkLocationPath(obj.LinkLocationPath, phase);
                    }
                }
            }
            private void Update_TargetFolderPath(global::System.String obj, int phase)
            {
                if ((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
                {
                    // MasterEntryControl.xaml line 41
                    XamlBindingSetters.Set_Windows_UI_Xaml_Controls_TextBox_Text(this.obj2, obj, null);
                }
            }
            private void Update_LinkLocationPath(global::System.String obj, int phase)
            {
                if ((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
                {
                    // MasterEntryControl.xaml line 58
                    XamlBindingSetters.Set_Windows_UI_Xaml_Controls_TextBox_Text(this.obj4, obj, null);
                }
            }
            private void UpdateTwoWay_2_Text()
            {
                if (this.initialized)
                {
                    if (this.dataRoot != null)
                    {
                        this.dataRoot.TargetFolderPath = this.obj2.Text;
                    }
                }
            }
            private void UpdateTwoWay_4_Text()
            {
                if (this.initialized)
                {
                    if (this.dataRoot != null)
                    {
                        this.dataRoot.LinkLocationPath = this.obj4.Text;
                    }
                }
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18362.1")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private class MasterEntryControl_obj1_BindingsTracking
            {
                private global::System.WeakReference<MasterEntryControl_obj1_Bindings> weakRefToBindingObj; 

                public MasterEntryControl_obj1_BindingsTracking(MasterEntryControl_obj1_Bindings obj)
                {
                    weakRefToBindingObj = new global::System.WeakReference<MasterEntryControl_obj1_Bindings>(obj);
                }

                public MasterEntryControl_obj1_Bindings TryGetBindingObject()
                {
                    MasterEntryControl_obj1_Bindings bindingObject = null;
                    if (weakRefToBindingObj != null)
                    {
                        weakRefToBindingObj.TryGetTarget(out bindingObject);
                        if (bindingObject == null)
                        {
                            weakRefToBindingObj = null;
                            ReleaseAllListeners();
                        }
                    }
                    return bindingObject;
                }

                public void ReleaseAllListeners()
                {
                    UpdateChildListeners_(null);
                }

                public void DependencyPropertyChanged_TargetFolderPath(global::Windows.UI.Xaml.DependencyObject sender, global::Windows.UI.Xaml.DependencyProperty prop)
                {
                    MasterEntryControl_obj1_Bindings bindings = TryGetBindingObject();
                    if (bindings != null)
                    {
                        global::FolderLinkCreator.UWPUI.MasterEntryControl obj = sender as global::FolderLinkCreator.UWPUI.MasterEntryControl;
                        if (obj != null)
                        {
                            bindings.Update_TargetFolderPath(obj.TargetFolderPath, DATA_CHANGED);
                        }
                    }
                }
                public void DependencyPropertyChanged_LinkLocationPath(global::Windows.UI.Xaml.DependencyObject sender, global::Windows.UI.Xaml.DependencyProperty prop)
                {
                    MasterEntryControl_obj1_Bindings bindings = TryGetBindingObject();
                    if (bindings != null)
                    {
                        global::FolderLinkCreator.UWPUI.MasterEntryControl obj = sender as global::FolderLinkCreator.UWPUI.MasterEntryControl;
                        if (obj != null)
                        {
                            bindings.Update_LinkLocationPath(obj.LinkLocationPath, DATA_CHANGED);
                        }
                    }
                }
                private long tokenDPC_TargetFolderPath = 0;
                private long tokenDPC_LinkLocationPath = 0;
                public void UpdateChildListeners_(global::FolderLinkCreator.UWPUI.MasterEntryControl obj)
                {
                    MasterEntryControl_obj1_Bindings bindings = TryGetBindingObject();
                    if (bindings != null)
                    {
                        if (bindings.dataRoot != null)
                        {
                            bindings.dataRoot.UnregisterPropertyChangedCallback(global::FolderLinkCreator.UWPUI.MasterEntryControl.TargetFolderPathProperty, tokenDPC_TargetFolderPath);
                            bindings.dataRoot.UnregisterPropertyChangedCallback(global::FolderLinkCreator.UWPUI.MasterEntryControl.LinkLocationPathProperty, tokenDPC_LinkLocationPath);
                        }
                        if (obj != null)
                        {
                            bindings.dataRoot = obj;
                            tokenDPC_TargetFolderPath = obj.RegisterPropertyChangedCallback(global::FolderLinkCreator.UWPUI.MasterEntryControl.TargetFolderPathProperty, DependencyPropertyChanged_TargetFolderPath);
                            tokenDPC_LinkLocationPath = obj.RegisterPropertyChangedCallback(global::FolderLinkCreator.UWPUI.MasterEntryControl.LinkLocationPathProperty, DependencyPropertyChanged_LinkLocationPath);
                        }
                    }
                }
                public void RegisterTwoWayListener_2(global::Windows.UI.Xaml.Controls.TextBox sourceObject)
                {
                    sourceObject.RegisterPropertyChangedCallback(global::Windows.UI.Xaml.Controls.TextBox.TextProperty, (sender, prop) =>
                    {
                        var bindingObj = this.TryGetBindingObject();
                        if (bindingObj != null)
                        {
                            bindingObj.UpdateTwoWay_2_Text();
                        }
                    });
                }
                public void RegisterTwoWayListener_4(global::Windows.UI.Xaml.Controls.TextBox sourceObject)
                {
                    sourceObject.RegisterPropertyChangedCallback(global::Windows.UI.Xaml.Controls.TextBox.TextProperty, (sender, prop) =>
                    {
                        var bindingObj = this.TryGetBindingObject();
                        if (bindingObj != null)
                        {
                            bindingObj.UpdateTwoWay_4_Text();
                        }
                    });
                }
            }
        }
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18362.1")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 3: // MasterEntryControl.xaml line 45
                {
                    this.targetFolderBrowseButton = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 5: // MasterEntryControl.xaml line 62
                {
                    this.linkLocationBrowseButton = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 6: // MasterEntryControl.xaml line 70
                {
                    this.createLinkButton = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18362.1")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            switch(connectionId)
            {
            case 1: // MasterEntryControl.xaml line 1
                {                    
                    global::Windows.UI.Xaml.Controls.UserControl element1 = (global::Windows.UI.Xaml.Controls.UserControl)target;
                    MasterEntryControl_obj1_Bindings bindings = new MasterEntryControl_obj1_Bindings();
                    returnValue = bindings;
                    bindings.SetDataRoot(this);
                    this.Bindings = bindings;
                    element1.Loading += bindings.Loading;
                }
                break;
            }
            return returnValue;
        }
    }
}

