#pragma checksum "C:\Users\attfl\Documents\Visual Studio 2019\Projects\FolderLinkCreator\FolderLinkCreator.UWPUI\MasterEntryControl.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "4810248DA1F2B9A34AC151E4896CF6F3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderLinkCreator.UWPUI
{
    partial class MasterEntryControl : 
        global::Windows.UI.Xaml.Controls.UserControl, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18362.1")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 2: // MasterEntryControl.xaml line 41
                {
                    this.TargetFolderTextBox = (global::Windows.UI.Xaml.Controls.TextBox)(target);
                }
                break;
            case 3: // MasterEntryControl.xaml line 45
                {
                    this.TargetFolderBrowseButton = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 4: // MasterEntryControl.xaml line 58
                {
                    this.LinkLocationTextBox = (global::Windows.UI.Xaml.Controls.TextBox)(target);
                }
                break;
            case 5: // MasterEntryControl.xaml line 62
                {
                    this.LinkLocationBrowseButton = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            case 6: // MasterEntryControl.xaml line 70
                {
                    this.CloseButton = (global::Windows.UI.Xaml.Controls.Button)(target);
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18362.1")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

